"""observations table

Revision ID: 7e49d208d5cd
Revises: e0452e496f21
Create Date: 2026-01-28 16:48:06.412165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e49d208d5cd'
down_revision = 'e0452e496f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloudiness', sa.String(length=15), nullable=False),
    sa.Column('precipitation', sa.String(length=15), nullable=False),
    sa.Column('precipitation_rate', sa.String(length=15), nullable=True),
    sa.Column('snow_depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_created_at'))

    op.drop_table('observations')
    # ### end Alembic commands ###
